### PR TITLE
Fixes for compilation and test errors

### LINKED ISSUE #284: cookiestore tests are failing on Linux because of incorrect 'expires'
[2:17 AM] Jim Borden: Also the cookiestore tests are failing on Linux because of incorrect 'expires'
[2:20 AM] Jim Borden: I don't think strptime guarantees time zone correctness
[3:05 AM] Jim Borden: Indeed Windows doesn't even try to parse the %Z part, it just fails instead...

### LINKED ISSUE #285: ReplicatorAPITest build error on Windows
[2:12 AM] Jim Borden: Since I'm out tomorrow Jens could you take a look at something that doesn't compile on Windows now that I put in the replicator api test.  Line 98 of ReplicatorAPITest.hh is as follows:
[2:12 AM] Jim Borden:
    `if(_headers)`
[2:13 AM] Jim Borden: `_headers` is AllocedDict and windows says:
[2:13 AM] Jim Borden:
    `|  conditional expression of type 'fleeceapi::AllocedDict' is illegal`
[2:13 AM] Jim Borden: Changing it to `!!_headers` works though, so maybe that can be the workaround?

### PR DESCRIPTION
**Pull request by borrrden**
- Compilation error on windows using a class as a conditional
- Failure on multiple platforms with Cookie expiry parsing

Fixes #284 (cookiestore tests are failing on Linux because of incorrect 'expires')
Fixes #285 (ReplicatorAPITest build error on Windows)

### CODE REVIEW

File: Replicator/CookieStore.cc [hunk 1]
```diff
@@ -27,6 +27,29 @@ using namespace litecore::websocket;
 
 namespace litecore { namespace repl {
 
+	static int kTimeOffset = -1;
+
+	static void get_time_offset()
+	{
+		if (kTimeOffset != -1) {
```
Comment (snej) [inline Replicator/CookieStore.cc]: This needs to be thread-safe since it's global state cookies can be accessed by multiple replicators.
std::call_once would be a good way to initialize this.

File: Replicator/CookieStore.cc [hunk 2]
```diff
@@ -27,6 +27,29 @@ using namespace litecore::websocket;
 
 namespace litecore { namespace repl {
 
+	static int kTimeOffset = -1;
```
Comment (snej) [inline Replicator/CookieStore.cc]: Indentation is wonky here; looks like you're using tabs to indent.

File: Replicator/CookieStore.cc [hunk 3]
```diff
@@ -61,11 +84,14 @@ namespace litecore { namespace repl {
...
                 if (expires == 0) {
-                    struct tm datetime;
-                    if (strptime(val.c_str(), "%a, %d %b %Y %T %Z", &datetime) == NULL) {
+                    struct tm datetime = { 0 };
+                    if (strptime(val.c_str(), "%a, %d %b %Y %T", &datetime) == NULL) {
                         Warn("Couldn't parse Expires in cookie");
                         return;
                     }
+
+					get_time_offset();
```
Comment (snej) [inline Replicator/CookieStore.cc]: Fix indentation

File: Replicator/CookieStore.cc [hunk 4]
```diff
@@ -61,11 +84,14 @@ namespace litecore { namespace repl {
                 secure = true;
             } else if (key == "Expires") {
                 if (expires == 0) {
-                    struct tm datetime;
-                    if (strptime(val.c_str(), "%a, %d %b %Y %T %Z", &datetime) == NULL) {
+                    struct tm datetime = { 0 };
```
Comment (snej) [inline Replicator/CookieStore.cc]: Could you break this whole block out into a function that takes a string and returns a time_t, and put it at the bottom of the file? That would make things cleaner.

**Comment by borrrden** [comment]
Shoot!  I had to reinstall Windows the other day and it messed with my spacing settings.  I'll get that remedied quick.
