### PR TITLE
Cap 32-bit linux cookie date to the max value

### LINKED ISSUE #510: Cookie test failures on 32-bit Linux due to year 2038 bug
The cookie implementation uses mktime(), the 32-bit version of which can't cope with the far-future date of 2099 that the test code uses. This causes a few assertions to fail when running on 32-bit platforms, for instance

```
Cookie Parser
  Expires
-----------------------------------------------------------------------------------------------------------------------
/var/data/rlc/poky/build-nanoscope/tmp/work/cortexa9hf-neon-oe-linux-gnueabi/couchbase-lite-core/2.0-r0/git/Replicator/tests/CookieStoreTest.cc:21
.......................................................................................................................

/var/data/rlc/poky/build-nanoscope/tmp/work/cortexa9hf-neon-oe-linux-gnueabi/couchbase-lite-core/2.0-r0/git/Replicator/tests/CookieStoreTest.cc:90: FAILED:
  CHECK( c.expires == 4084683494 )
with expansion:
  -1 == 4084683494 (0xf37752e6)

```

### PR DESCRIPTION
**Pull request by borrrden**
Alter the test to check such.  Fixes #510.

### CODE REVIEW

File: Replicator/CookieStore.cc [hunk 1]
```diff
@@ -36,8 +36,54 @@ using namespace fleece;
...
+        inputTime->tm_isdst = 0;
+    }
+
+    static void adjust_for_overflow(struct tm* inputTime)
+    {
+        if(sizeof(time_t) > 4 || inputTime->tm_year < 138) {
+            return;
+        }
+
+        if(inputTime->tm_mon > 0) {
```
Comment (snej) [inline Replicator/CookieStore.cc]: Please combine all five of these tests into one with `||`. Then since there's only one call to `cap_to_max`, you can move that into the body of the `if`.
(Sorry to be picky, but this code can be so much smaller without losing clarity.)

Comment (borrrden) [reply Replicator/CookieStore.cc]: I wanted to do that but this is not just one condition.  For example, I only care if the seconds are greater than 7 if the minutes are <= 14.  Otherwise any time with seconds greater then 7 will get capped.  Am I having a brain fart?

Comment (borrrden) [reply Replicator/CookieStore.cc]: This just made me realize that what I wrote doesn't actually achieve what I want...hold on that
