### PR TITLE
Fixed #115 - Crash in litecore::error::_throw()

### LINKED ISSUE #115: Crash in litecore::error::_throw()
LiteCore version CBL Android 2.0 uses:  0da3d6c7d90b51281661986f450a1f79457b70b2

`c4db_delete()` operation causes crash in `throw()` if db state is busy.

```
05-10 20:38:25.433 9265-9278/? E/BaseTest: setUp
                                           
                                           [ 05-10 20:38:25.433  9265: 9278 I/LiteCore DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DBite2
                                           
                                           Opening Data[ 05-10 20:38:25.441  9265: 9278 I/LiteCore DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DBite2
                                           
                                           OpDataFile: begin trans[ 05-10 20:38:25.441  9265: 9278 I/LiteCore DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DBite2
                                           
                                           OpDataFile: commit trans[ 05-10 20:38:25.441  9265: 9278 E/DatabaseTest ]
                                           setUp
                                           
                                           [ 05-10 20:38:25.441  9265: 9278 I/LiteCore DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DBite2
                                           
                                           OpOpening Da[ 05-10 20:38:28.459  9265: 9278 E/LiteCore DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DB DBite2
                                           
                                           OpLiteCore throwing LiteCore error 24: database busy/[ 05-10 20:38:28.459  9265: 9278 E/libLiteCore ]
                                           /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so litecore::error::_throw()
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so litecore::error::_throw(litecore::error::Domain, int)
05-10 20:38:28.459 9265-9278/? E/libLiteCore: ??? 
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so litecore::SQLiteDataFile::deleteDataFile()
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so c4Internal::Database::deleteDatabase()
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so void litecore::function_ref<void ()>::callback_fn<std::__ndk1::__bind<void (c4Internal::Database::*)(), c4Database*&> >(int)
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so litecore::function_ref<void ()>::operator()() const
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so c4Internal::tryCatch(C4Error*, litecore::function_ref<void ()>)
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so c4db_delete
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so Java_com_couchbase_litecore_Database_delete
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/oat/x86/base.odex oatexec
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/oat/x86/base.odex oatexec
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/oat/x86/base.odex oatexec
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/app/com.couchbase.lite.test-1/oat/x86/base.odex oatexec
05-10 20:38:28.459 9265-9278/? E/libLiteCore: ??? 
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /system/lib/libart.so art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /system/lib/libart.so art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)
05-10 20:38:28.459 9265-9278/? E/libLiteCore: ??? 
05-10 20:38:28.459 9265-9278/? E/libLiteCore: /data/dalvik-cache/x86/system@framework@boot.oat oatexec
05-10 20:38:28.459 9265-9278/? A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x42442042 in tid 9278 (roidJUnitRunner)
05-10 20:38:28.565 223-223/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-10 20:38:28.565 223-223/? A/DEBUG: Build fingerprint: 'Android/vbox86p/vbox86p:6.0/MRA58K/genymotion03201937:userdebug/test-keys'
05-10 20:38:28.565 223-223/? A/DEBUG: Revision: '0'
05-10 20:38:28.565 223-223/? A/DEBUG: ABI: 'x86'
05-10 20:38:28.565 223-223/? A/DEBUG: pid: 9265, tid: 9278, name: roidJUnitRunner  >>> com.couchbase.lite.test <<<
05-10 20:38:28.565 223-223/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x42442042
05-10 20:38:28.569 223-223/? A/DEBUG:     eax 42442042  ebx 434c4e47  ecx e055df10  edx 00000001
05-10 20:38:28.569 223-223/? A/DEBUG:     esi eea56130  edi e04b5013
05-10 20:38:28.569 223-223/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000004f  xss 0000002b
05-10 20:38:28.569 223-223/? A/DEBUG:     eip e049b9ae  ebp e07d1828  esp e07d17b0  flags 00210282
05-10 20:38:28.573 223-223/? A/DEBUG: backtrace:
05-10 20:38:28.573 223-223/? A/DEBUG:     #00 pc 004fe9ae  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so
05-10 20:38:28.573 223-223/? A/DEBUG:     #01 pc 004fe515  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (__gxx_personality_v0+261)
05-10 20:38:28.573 223-223/? A/DEBUG:     #02 pc 00512170  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so
05-10 20:38:28.573 223-223/? A/DEBUG:     #03 pc 004fd3a9  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (__cxa_throw+105)
05-10 20:38:28.573 223-223/? A/DEBUG:     #04 pc 0015ef91  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (litecore::error::_throw()+401)
05-10 20:38:28.573 223-223/? A/DEBUG:     #05 pc 0015f0f2  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (litecore::error::_throw(litecore::error::Domain, int)+194)
05-10 20:38:28.573 223-223/? A/DEBUG:     #06 pc 0015f37b  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (litecore::error::_throw(litecore::error::LiteCoreError)+59)
05-10 20:38:28.573 223-223/? A/DEBUG:     #07 pc 0021c4aa  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (litecore::SQLiteDataFile::deleteDataFile()+218)
05-10 20:38:28.573 223-223/? A/DEBUG:     #08 pc 001dcb84  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (c4Internal::Database::deleteDatabase()+196)
05-10 20:38:28.573 223-223/? A/DEBUG:     #09 pc 00175db3  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (void litecore::function_ref<void ()>::callback_fn<std::__ndk1::__bind<void (c4Internal::Database::*)(), c4Database*&> >(int)+211)
05-10 20:38:28.573 223-223/? A/DEBUG:     #10 pc 001824cc  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (litecore::function_ref<void ()>::operator()() const+44)
05-10 20:38:28.573 223-223/? A/DEBUG:     #11 pc 001823fe  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (c4Internal::tryCatch(C4Error*, litecore::function_ref<void ()>)+46)
05-10 20:38:28.573 223-223/? A/DEBUG:     #12 pc 00172a3d  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (c4db_delete+317)
05-10 20:38:28.573 223-223/? A/DEBUG:     #13 pc 00131975  /data/app/com.couchbase.lite.test-1/lib/x86/libLiteCoreJNI.so (Java_com_couchbase_litecore_Database_delete+101)
05-10 20:38:28.573 223-223/? A/DEBUG:     #14 pc 00a54f74  /data/app/com.couchbase.lite.test-1/oat/x86/base.odex (offset 0x6a0000) (void com.couchbase.litecore.Database.delete()+104)
05-10 20:38:28.573 223-223/? A/DEBUG:     #15 pc 00a3b5a1  /data/app/com.couchbase.lite.test-1/oat/x86/base.odex (offset 0x6a0000) (void com.couchbase.lite.Database.deleteC4DB()+69)
05-10 20:38:28.573 223-223/? A/DEBUG:     #16 pc 00a3e171  /data/app/com.couchbase.lite.test-1/oat/x86/base.odex (offset 0x6a0000) (void com.couchbase.lite.Database.delete()+101)
05-10 20:38:28.573 223-223/? A/DEBUG:     #17 pc 00d7ef76  /data/app/com.couchbase.lite.test-1/oat/x86/base.odex (offset 0x6a0000) (void com.couchbase.lite.DatabaseTest.testDeleteDBOpenedByOtherInstance()+250)
05-10 20:38:28.573 223-223/? A/DEBUG:     #18 pc 00137ab2  /system/lib/libart.so (art_quick_invoke_stub+338)
05-10 20:38:28.573 223-223/? A/DEBUG:     #19 pc 001435f4  /system/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+212)
05-10 20:38:28.573 223-223/? A/DEBUG:     #20 pc 0050ec68  /system/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1736)
05-10 20:38:28.573 223-223/? A/DEBUG:     #21 pc 0048b9f3  /system/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobject*)+80)
05-10 20:38:28.573 223-223/? A/DEBUG:     #22 pc 726a0ca4  /data/dalvik-cache/x86/system@framework@boot.oat (offset 0x1eb7000)
05-10 20:38:28.612 223-223/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
05-10 20:38:28.612 223-223/? E/DEBUG: AM write failed: Broken pipe
```

### PR DESCRIPTION
**Pull request by hideki**
- Incorrectly handle domain value for Android case. This caused the crash in the exception.

### CODE REVIEW

**Comment by snej** [comment]
I looked up the API, and there's a `__android_log_vprint` function in the NDK. If you use that in place of `vfprintf`, the Android case will be almost identical to the other case.

**Comment by hideki** [comment]
Applied `__android_log_vprint`. Could you please rereview the PR?

File: LiteCore/Support/Logging.cc [hunk 1]
```diff
@@ -48,8 +49,11 @@ namespace litecore {
 
     LogLevel LogDomain::sCallbackMinLevel = LogLevel::Info;
     static LogDomain::Callback_t sCallback = defaultCallback;
+#if __ANDROID__
+    static bool sCallbackPreformatted = true;
```
Comment (snej) [inline LiteCore/Support/Logging.cc]: This is incorrect, now that you're formatting the string. It can cause crashes if the formatted string contains a `%` character.

File: LiteCore/Support/Logging.cc [hunk 2]
```diff
@@ -230,25 +234,20 @@ namespace litecore {
...
+
+        auto name = domain.name();
+        static const char *kLevels[] = {"***", "", "", "WARNING", "ERROR"};
+        #if ANDROID
+            stringstream buf;
+            LogDecoder::writeHeader(kLevels[(int) level], name, buf);
+            static const int androidLevels[5] = {ANDROID_LOG_DEBUG, ANDROID_LOG_INFO,
+                                                 ANDROID_LOG_INFO, ANDROID_LOG_WARN,
+                                                 ANDROID_LOG_ERROR};
+            __android_log_vprint(androidLevels[(int) level], buf.str().c_str(), fmt, args);
```
Comment (snej) [inline LiteCore/Support/Logging.cc]: The result of `LogDecoder::writeHeader` is a combination of the domain name and level with brackets, like `[Query] WARNING:`. That doesn't seem like the right thing to pass as the tag to the log — isn't it supposed to be just `LiteCore` plus the domain name, as before?
