### PR TITLE
Remove spaghetti flow between LogDomain and LogEncoder

### LINKED ISSUE #680: Deadlock running unit tests, in LogDomain::getObject
Just reproduced the hang that Kim has seen on the build machines, while running a replicator unit test. Here's the backtrace. It looks like a re-entrant lock in the logging code.

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff70d63e76 libsystem_kernel.dylib`__psynch_mutexwait + 10
    frame #1: 0x0000000104f798af libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_wait + 114
    frame #2: 0x0000000104f76e76 libsystem_pthread.dylib`_pthread_mutex_firstfit_lock_slow + 235
    frame #3: 0x00007fff6e2f8b29 libc++.1.dylib`std::__1::mutex::lock() + 9
    frame #4: 0x00000001008949de LiteCoreCppTests`std::__1::unique_lock<std::__1::mutex>::unique_lock(this=0x0000000107de4530, __m=0x00000001027905e0) at __mutex_base:131:61
    frame #5: 0x0000000100888707 LiteCoreCppTests`std::__1::unique_lock<std::__1::mutex>::unique_lock(this=0x0000000107de4530, __m=0x00000001027905e0) at __mutex_base:131:54
    frame #6: 0x00000001009f6945 LiteCoreCppTests`litecore::LogDomain::getObject(ref=1) at Logging.cc:517:28
    frame #7: 0x0000000100f160e6 LiteCoreCppTests`litecore::LogEncoder::vlog(this=0x0000617000009a80, domain="DB", object=1, format="instantiated on %s", args=0x0000000107cc7b20) at LogEncoder.cc:101:22
    frame #8: 0x00000001009f4662 LiteCoreCppTests`litecore::LogDomain::dylog(this=0x0000000102e323a0, level=Info, domain="DB", objRef=1, fmt="instantiated on %s", args=0x0000000107cc7b20) at Logging.cc:460:38
    frame #9: 0x00000001009f3564 LiteCoreCppTests`litecore::LogDomain::vlog(this=0x0000000102e323a0, level=Info, objRef=1, doCallback=true, fmt="instantiated on %s", args=0x0000000107cc7b20) at Logging.cc:421:13
    frame #10: 0x00000001009f97fe LiteCoreCppTests`litecore::Logging::_logv(this=0x0000613000008e00, level=Info, format="instantiated on %s", args=0x0000000107cc7b20) const at Logging.cc:607:17
    frame #11: 0x00000001009f8e83 LiteCoreCppTests`litecore::Logging::_log(this=0x0000613000008e00, level=Info, format="instantiated on %s") const at Logging.cc:591:9
    frame #12: 0x0000000100a5809a LiteCoreCppTests`litecore::DataFile::Shared::Shared(this=0x0000613000008e00, p="/private/var/folders/m4/fy45wyms33532xv1lcgd5x7r0000gn/T/Litecore_C_Tests/cbl_core_test.cblite2/db.sqlite3") at DataFile+Shared.hh:148:13
    frame #13: 0x0000000100a4ecd7 LiteCoreCppTests`litecore::DataFile::Shared::Shared(this=0x0000613000008e00, p="/private/var/folders/m4/fy45wyms33532xv1lcgd5x7r0000gn/T/Litecore_C_Tests/cbl_core_test.cblite2/db.sqlite3") at DataFile+Shared.hh:147:9
    frame #14: 0x0000000100a3fed5 LiteCoreCppTests`litecore::DataFile::Shared::forPath(path=0x000061200000b918, dataFile=0x000061100000cac0) at DataFile+Shared.hh:34:28
    frame #15: 0x0000000100a3f89f LiteCoreCppTests`litecore::DataFile::DataFile(this=0x000061100000cac0, path=0x000061200000b918, delegate=0x000061200000b8c0, options=0x0000000108097c80) at DataFile.cc:114:19
    frame #16: 0x0000000100ae2cd0 LiteCoreCppTests`litecore::SQLiteDataFile::SQLiteDataFile(this=0x000061100000cac0, path=0x000061200000b918, delegate=0x000061200000b8c0, options=0x0000000108097c80) at SQLiteDataFile.cc:168:6
    frame #17: 0x0000000100ae2399 LiteCoreCppTests`litecore::SQLiteDataFile::SQLiteDataFile(this=0x000061100000cac0, path=0x000061200000b918, delegate=0x000061200000b8c0, options=0x0000000108097c80) at SQLiteDataFile.cc:169:5
    frame #18: 0x0000000100ae2302 LiteCoreCppTests`litecore::SQLiteDataFile::Factory::openFile(this=0x0000000102e37c40, path=0x000061200000b918, delegate=0x000061200000b8c0, options=0x0000000108097c80) at SQLiteDataFile.cc:153:20
    frame #19: 0x0000000100d8e3bb LiteCoreCppTests`c4Internal::Database::Database(this=0x000061200000b8c0, bundlePath="/var/folders/m4/fy45wyms33532xv1lcgd5x7r0000gn/T/Litecore_C_Tests/cbl_core_test.cblite2", inConfig=C4DatabaseConfig @ 0x0000000108097c20) at Database.cc:132:39
    frame #20: 0x0000000100febd1d LiteCoreCppTests`c4Database::c4Database(this=0x000061200000b8c0, path=0x0000000107f29420, config=C4DatabaseConfig @ 0x0000000107f29820) at Database.hh:190:6
    frame #21: 0x0000000100feb97b LiteCoreCppTests`c4Database::c4Database(this=0x000061200000b8c0, path=0x0000000107f29420, config=C4DatabaseConfig @ 0x0000000107cc5320) at Database.hh:190:29
    frame #22: 0x0000000100a91be5 LiteCoreCppTests`c4db_open::$_0::operator(this=0x0000000107de1d60)() const at c4Database.cc:97:27
    frame #23: 0x0000000100a9184f LiteCoreCppTests`c4Database* fleece::function_ref<c4Database* ()>::callback_fn<c4db_open::$_0>(callable=4426964320) at function_ref.hh:59:12
    frame #24: 0x0000000100a91727 LiteCoreCppTests`fleece::function_ref<c4Database* ()>::operator(this=0x0000000107cb2d60)() const at function_ref.hh:72:12
    frame #25: 0x0000000100a891cc LiteCoreCppTests`c4Database* c4Internal::tryCatch<c4Database*>(outError=0x00007ffeefbfdbf0, fn=function_ref<c4Database *()> @ 0x0000000107cb2d60)>) at c4ExceptionUtils.hh:60:20
    frame #26: 0x0000000100a88f86 LiteCoreCppTests`::c4db_open(path=(buf = 0x000060800001ff20, size = 87), configP=0x00007ffeefbfd9f0, outError=0x00007ffeefbfdbf0) at c4Database.cc:96:12
    frame #27: 0x000000010096165a LiteCoreCppTests`C4Test::C4Test(this=0x0000000108094428, testOption=0) at c4Test.cc:243:10
    frame #28: 0x00000001008fe83d LiteCoreCppTests`ReplicatorLoopbackTest::ReplicatorLoopbackTest(this=0x0000000108094420) at ReplicatorLoopbackTest.hh:37:6
    frame #29: 0x00000001008fe63c LiteCoreCppTests`(anonymous namespace)::____C_A_T_C_H____T_E_S_T____44::____C_A_T_C_H____T_E_S_T____44(this=0x0000000108094420) at ReplicatorLoopbackTest.cc:44:1
...
```

### PR DESCRIPTION
**Pull request by borrrden**
Instead of LogEncoder asking for objects, provide them upfront.  This prevents a deadlock on LogDomain's mutex.

Fixes #680

### CODE REVIEW

**Comment by borrrden** [comment]
Ok that took entirely too long but now I've gotten a non-broken PR

File: LiteCore/Support/LogEncoder.cc [hunk 1]
```diff
@@ -81,7 +82,8 @@ namespace litecore {
         return int64_t(_st.elapsed() * kTicksPerSec);
     }
 
-    void LogEncoder::vlog(const char *domain, ObjectRef object, const char *format, va_list args) {
+    void LogEncoder::vlog(const char *domain, const map<unsigned, string> &objectMap,
+        ObjectRef object, const char *format, va_list args) {
```
Comment (snej) [inline LiteCore/Support/LogEncoder.cc]: If you have a chance could you indent this to line up with the `(` on the prev line?

File: LiteCore/Support/Logging.cc [hunk 2]
```diff
@@ -179,7 +179,7 @@ namespace litecore {
         if(encoder) {
             auto newEncoder = new LogEncoder(*sFileOut[(int)level], level);
             sLogEncoder[(int)level] = newEncoder;
-            newEncoder->log("", LogEncoder::None, "---- %s ----", sInitialMessage.c_str());
+            newEncoder->log("", map<unsigned, string>(), LogEncoder::None, "---- %s ----", sInitialMessage.c_str());
```
Comment (snej) [inline LiteCore/Support/Logging.cc]: Tip: you can simplify that new parameter to just `{}`. (No need to change it here unless you want to.)
